---
- name: Converge
  hosts: all
  vars:
    custom_rules:
      - rule: allow
        port: 443
      - rule: allow
        port: 80
      - rule: allow
        port: 9080
        src: "10.2.1.0/24"
      - rule: allow
        port: 9100
        src: "10.2.1.0/24"

  roles:
    - role: genlab.ufw
      disable_ipv6: true
      rules: "{{ custom_rules }}"
