---
- name: Converge
  hosts: all
  vars:
    custom_rules:
      - rule: allow
        port: 80
      - rule: allow
        port: 9080
        src: "10.2.1.0/24"
      - rule: allow
        interface: eth0@if288
        direction: in

  roles:
    - role: genlab.ufw
      disable_ipv6: true
      limit_ssh: true
      rules: "{{ custom_rules }}"
