---
name: molecule
  
on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:

  molecule:
    name: molecule
    runs-on: ubuntu-latest

    strategy:
      matrix:
        distro:
          - ubuntu2404
          - ubuntu2204
          - ubuntu2004

    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@29d0a406a44cd30f78c79aa44683acbf49ebc6b4
        with:
          micromamba-version: '1.5.8-0'
          environment-file: environment.ci.yml
          init-shell: bash
          post-cleanup: 'all'

      - name: Run Molecule tests
        run: molecule test
        shell: micromamba-shell {0}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
